### ISSUE TITLE
how to change 

### ISSUE THREAD

**Issue by lusento** [kabirjaipal/real-giveaways#4]
how to change the button text and its color?
the color of the button is success, I want to change it to primary, but I can't do it, I can't change the text by default "Join" either. How do I do this?

an excerpt of the code and img 

```

const manager = new CustomManager(client, {
  embedColor: Colors.Blurple,
  pingEveryone: false,
  emoji: "🎁",
});

```
 ![image](https://github.com/user-attachments/assets/caad112b-fd5c-443f-a553-1409042351bf)

**Comment by himitsu95** [comment]
check the src/Manager.js line 234
![image](https://github.com/user-attachments/assets/f4f64809-7474-4d3a-9f25-6645aaa58f1b)
